### ISSUE TITLE
Conflict between [Source]ModifyMove and RedirectTarget

### ISSUE THREAD

**Issue by ascriptmaster** [Zarel/Pokemon-Showdown#1480]
If a Pokemon with Unaware uses Follow Me to redirect an attack, the attack will still count the attacker's stat changes.

**Comment by ascriptmaster** [comment]
(It would be nice if we could just fire off `ModifyMove` one more time if the `RedirectTarget` event is successful, but that could cause the opposite bug if a Pokemon without Unaware uses Follow Me to redirect an attack away from an Unaware Pokemon. I'm not really sure.)

**Comment by Slayer95** [comment]
This affects everything else with <code>onSourceModifyMove</code> handlers: Foresight, Miracle Eye, and Telekinesis.
Maybe it's time to split the <code>Source</code> handlers off?

**Comment by Zarel** [comment]
So we need to modify targets before we do the ModifyMove handlers.

**Comment by ascriptmaster** [comment]
Also noting here that Unaware's interaction with multi-target moves is incorrect as well, not counting the attacker's stat changes even on the Pokemon without Unaware.

**Comment by Zarel** [comment]
Maybe just hardcode `ability.ignoreBoosts` like we do for the move `ignoreDefensive` etc flags.

**Comment by ascriptmaster** [comment]
This is (most likely) fixed in #1502, using the exact suggestions you just made.

**Comment by Slayer95** [comment]
Foresight, Miracle Eye, and Telekinesis are still broken.

(I don't feel like opening a new issue for them lol)

**Comment by ascriptmaster** [comment]
From what I see on various sites, Foresight does not work the way it's coded in our server.

Veekun says that it resets the target's positive evasion boosts to normal and prevents further boosting, while Bulbapedia and Serebii only mention resetting the evasion.

However, our server has it so it ignores the positive evasion boosts instead. Is this the actual behavior? @Marty-D 

This won't fix Telekinesis, but it's important that we make sure the moves are working as intended.

**Comment by ascriptmaster** [comment]
Probably the best fix for Telekinesis would be to have it imitate No Guard: use an `onAccuracy` handler and return `true`.

**Comment by Zarel** [comment]
it doesn't? blah, what have you guys been doing? -_-

**Comment by ascriptmaster** [comment]
Marty says our server implementation is correct...

**Comment by ascriptmaster** [comment]
I feel like the Pokemon should hold the `ignoreEvasion` and other ignoreStat properties. This will make Foresight and Miracle Eye easy to do (just use the `'ModifyPokemon'` event). Also, for the sake of consistency, we'd want Unaware to use `'ModifyPokemon'` event, but then we'd use up extra cycles for the event system...

**Comment by ascriptmaster** [comment]
Telekinesis is being fixed in #1530, alongside Lock On, which also was having problems in Doubles.

**Comment by ascriptmaster** [comment]
Oh yeah, Foresight and Miracle Eye got fixed in #1665. Is that the last thing that needs fixing in here?
